### ISSUE TITLE
S2GPS - Síntesis Calidad de Software

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Yabin-2021#1]
[S2GPS 01 - Síntesis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Yabin-2021/files/9569283/S2GPS.01.-.Sintesis.pdf)

**Comment by CxrlosMX** [comment]
Buen trabajo compañero
Calificación obtenida: 18%
